name = "comment"
main = "worker.js"
compatibility_date = "2024-11-01"

[triggers]
crons = [
  "2-59/4 * * * *",     # 10:02, 10:06, 10:10, 10:14... (har 4 min)
  "5-59/4 * * * *",     # 10:05, 10:09, 10:13, 10:17... (har 4 min)
  "30 18 * * *"         # 18:30 UTC = 12:00 AM IST (reset)
]

[vars]
PHP_API_URL = "https://amittg.online/yt/api.php"

# KV Namespace
[[kv_namespaces]]
binding = "API_DATA"
id = "b9667df1d4f343179d537e221566819f"